# Python
FROM python:3.11.5-alpine3.18

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install build dependencies
RUN apk --no-cache add postgresql-dev gcc musl-dev

# Install dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project files into the docker image
COPY . /app/

# # Check if gunicorn is in requirements.txt
# RUN if ! pip show gunicorn > /dev/null; then \
#         echo "gunicorn not found in requirements.txt"; \
#         exit 1; \
#     fi

# Collect static files
# RUN python manage.py collectstatic --noinput
