version: '3'

services:
  django:
    build: 
      context: .
    command: ./django-static.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db

  nginx:
    image: nginx:1.25.2-alpine
    container_name: project_novel-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - django

  db:
    image: postgres:16.0
    container_name: project_novel-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}

volumes:
  postgres_data:
  static_volume:
