# Generated by Django 4.2.3 on 2023-08-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="prompt",
            field=models.TextField(max_length=500),
        ),
    ]
